services:
  web:
    build:
      context: .
      target: development
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/pysetup
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - api_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_api_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=django_pass_123
    ports:
      - "5432:5432"

volumes:
  api_db_data: