# Generated by Django 5.1.3 on 2024-12-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, default='Anonymous', max_length=255),
        ),
    ]
